config/routes.rb
Rails.application.routes.draw do
  get 'proyects/index'
  root 'proyects#index'
  post 'proyects/create'
  post 'proyects/index'
  get 'dashboard', to: 'proyects#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
    validates :name, :description, :state, presence: true
    enum state: [:propuesta, :en_progreso, :terminado]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
http_basic_authenticate_with name: 'desafiovamoscontodo', password: 'XAHTJEAS23123%23', only: :dashboard

  def index
    @proyect = Proyect.new
    @states = Proyect.states.keys.to_a
  end

  def create
    @proyect = Proyect.create(proyect_params)
  end

  def dashboard
    if params[:state].present?
      @proyects = Proyect.where('state = ?', params[:state])
      else
      @proyects = Proyect.all
    end
  end

  private

  def proyect_params
    params.require(:proyect).permit(:name, :description, :start_on, :end_on, :state)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proyects/dashboard.html.erb
<form>
<select name = "state">
    <option value = >:)</option>
    <option value = 0 >Propuesta</option>
    <option value = 1 >En progreso</option>
    <option value = 2 >Termino</option>
</select>
<button type = "submit"> Buscar</button>
</form>

<% @proyects.each do |p| %>
    <%= p.name %>
    <%= p.description %>
    <%= p.start_on %>
    <%= p.end_on %>
    <%= p.state %>
<% end %>

app/views/proyects/index.html.erb
<ul>
<%= form_with(model: @proyect, url: proyects_index_path, local:true) do |f| %>
<li><%= f.text_field :name %></li>
<li><%= f.text_area :description%></li>
<li><%= f.date_select :start_on %></li>
<li><%= f.date_select :end_on %></li>
<li><%= f.select :state, @states, {include_blank: true} %></li>
<li><%= f.submit %></li>
<% end %>
</ul>